version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "80:80"
    volumes:
      - ./lco_global:/lco_global
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
      build: .
      container_name: django1
      volumes:
        - ./lco_global:/lco_global
      expose:
        - "80"
      mem_limit: 256m
      environment:
        - MEZZ_DB_HOST=db1.lco.gtn
        - MEZZ_DB_USER=main_website
        - MEZZ_DB_PASSWD=main_website
        - MEZZ_DB_NAME=main_website
