# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0003_auto_20160811_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='seminardate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seminar date/time'),
        ),
    ]
