#!/bin/bash

TOPDIR="/var/www/apps/lco_global"

# Generate cron wrapper to set correct environment variables
cat > $TOPDIR/cronwrapper << EOF
export PYTHONPATH="${PYTHONPATH}"
export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}"

export MEZZ_DB_NAME="${MEZZ_DB_NAME}"
export MEZZ_DB_HOST="${MEZZ_DB_HOST}"
export MEZZ_DB_USER="${MEZZ_DB_USER}"
export MEZZ_DB_PASSWD="${MEZZ_DB_PASSWD}"

export ADS_TOKEN="${ADS_TOKEN}"

EOF

echo "default-time-zone = 'UTC'" >> /etc/my.cnf

# Make cron wrapper executable
chmod +x $TOPDIR/cronwrapper

# Django static files
python $TOPDIR/manage.py collectstatic --noinput

python $TOPDIR/manage.py migrate

# Upload the latest version of the data for the django_lcogtbiblio (Bibliometrics) app
#python $TOPDIR/manage.py loaddata $TOPDIR/fixtures/biblio_snapshot.json

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
