# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcopage',
            name='no_links',
            field=models.BooleanField(default=False, help_text="Check this if you don't want a links section in the footer", verbose_name='No links in footer'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminardate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 17, 59, 58, 241927), verbose_name='Seminar date/time'),
        ),
    ]
