# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0005_auto_20160929_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='speaker_name',
            field=models.CharField(default=b'tdb', max_length=255),
        ),
    ]
