# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170411_0504'),
        ('lcogt', '0006_auto_20161013_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('related_activity', models.ManyToManyField(blank=True, to='lcogt.Activity', verbose_name='Related activities')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'SpaceBook page',
            },
            bases=('pages.page',),
        ),
    ]
