# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-09 10:28
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0010_auto_20180406_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='agerange',
            field=mezzanine.core.fields.MultiChoiceField(choices=[(b'6', b'6-11'), (b'11', b'11-16'), (b'16', b'16-18'), (b'all', b'All')], default=b'all', help_text='What is the age range for this activity?', max_length=20),
        ),
    ]
