# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0011_auto_20180409_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'LCO Person', 'verbose_name_plural': 'LCO People'},
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, help_text='Only to be used for past post-docs', max_length=100, verbose_name='institute they are now'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_doc',
            field=models.BooleanField(default=False, verbose_name='post-doc in the science team'),
        ),
    ]
