# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0012_auto_20180511_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='science_team',
        ),
        migrations.AddField(
            model_name='profile',
            name='new_institute',
            field=models.CharField(blank=True, help_text='Only to be used for past post-docs', max_length=100, verbose_name='institute moved to'),
        ),
        migrations.AddField(
            model_name='profile',
            name='scientist',
            field=models.BooleanField(default=False, verbose_name='staff scientist'),
        ),
    ]
