# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-04 16:51
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0015_partnerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True, default='', help_text='Main content', verbose_name='About '),
        ),
    ]
