# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-05 13:52
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0017_partnerpage_partner_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='audience_type',
            field=mezzanine.core.fields.MultiChoiceField(choices=[('a', 'In-person workshops/training/mentoring'), ('b', 'Online workshops/training/mentoring'), ('c', 'General audience'), ('d', 'Citizen science')], default='all', help_text='What type of audience?', max_length=20, verbose_name='Audience type'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='region',
            field=mezzanine.core.fields.MultiChoiceField(choices=[('a', 'Europe'), ('b', 'Sub-Saharan Africa'), ('d', 'Northern Africa'), ('e', 'Northern America'), ('f', 'Latin America and Caribean'), ('g', 'Oceania'), ('h', 'Asia')], default='all', help_text='Where is your audience based?', max_length=20, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True, default='', help_text='Main content', verbose_name='About'),
        ),
    ]
