# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-05 16:41
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0018_auto_20190205_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('_order',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='region',
            field=mezzanine.core.fields.MultiChoiceField(choices=[('a', 'Europe'), ('b', 'Sub-Saharan Africa'), ('d', 'Northern Africa'), ('e', 'Northern America'), ('f', 'Latin America and Caribean'), ('g', 'Oceania'), ('h', 'Asia'), ('x', 'Online only')], default='all', help_text='Where is your audience based?', max_length=20, verbose_name='Region'),
        ),
    ]
