# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcogt', '0002_auto_20160725_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lcopage',
            options={'ordering': ('_order',), 'verbose_name': 'LCO Page+', 'verbose_name_plural': 'LCO Pages+'},
        ),
    ]
